package tests;// Generated by Selenium IDE

import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;

import java.util.*;

import static io.github.bonigarcia.wdm.DriverManagerType.CHROME;
import static org.junit.Assert.assertEquals;

public class AddExtraCoinsTest {

    private static final String ADMIN_USERNAME = "krusty";
    private static final String ADMIN_PASSWORD = "krab";

    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() {
        WebDriverManager.getInstance(CHROME).setup();
        driver = new ChromeDriver();

        js = (JavascriptExecutor) driver;
        vars = new HashMap<>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void addExtraCoins() {
        driver.get("http://localhost:8080/");
        driver.manage().window().setSize(new Dimension(1552, 840));
        driver.findElement(By.linkText("Sign in")).click();
        driver.findElement(By.name("username")).sendKeys(ADMIN_USERNAME);
        driver.findElement(By.name("password")).sendKeys(ADMIN_PASSWORD);
        driver.findElement(By.cssSelector("body")).click();
        driver.findElement(By.cssSelector(".basic")).click();

        driver.findElement(By.linkText("Add extra coins")).click();
        driver.findElement(By.cssSelector("body")).click();
        driver.findElement(By.id("value")).clear();
        driver.findElement(By.id("value")).sendKeys("2000");
        driver.findElement(By.cssSelector(".blue")).click();

        assertEquals("Value: 2000", driver.findElement(By.xpath("/html/body/div[3]/div[1]/span")).getText());

        driver.findElement(By.linkText("Submit another extra coins")).click();
        assertEquals("Add extra coins", driver.findElement(By.xpath("/html/body/div[3]/h3")).getText());
    }
}
