package tests;// Generated by Selenium IDE

import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;

import java.util.*;

import static io.github.bonigarcia.wdm.DriverManagerType.CHROME;
import static org.junit.Assert.assertEquals;

public class AddNewToolTest {

    private static final String CHEF_USERNAME = "chef";
    private static final String CHEF_PASSWORD = "chef";

    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() {
        WebDriverManager.getInstance(CHROME).setup();
        driver = new ChromeDriver();

        js = (JavascriptExecutor) driver;
        vars = new HashMap<>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void addNewTool() {
        driver.get("http://localhost:8080/");
        driver.manage().window().setSize(new Dimension(1552, 840));
        driver.findElement(By.linkText("Sign in")).click();
        driver.findElement(By.cssSelector("body")).click();
        driver.findElement(By.name("username")).clear();
        driver.findElement(By.name("username")).sendKeys(CHEF_USERNAME);
        driver.findElement(By.name("password")).click();
        driver.findElement(By.name("password")).clear();
        driver.findElement(By.name("password")).sendKeys(CHEF_PASSWORD);
        driver.findElement(By.cssSelector(".basic")).click();
        driver.findElement(By.linkText("Add new tool")).click();
        driver.findElement(By.id("name")).click();
        driver.findElement(By.id("name")).clear();
        driver.findElement(By.id("name")).sendKeys("TestTool");
        driver.findElement(By.id("status")).click();
        driver.findElement(By.id("status")).clear();
        driver.findElement(By.id("status")).sendKeys("500");
        driver.findElement(By.cssSelector(".blue")).click();

        assertEquals("Tool: name - TestTool, status - 500", driver.findElement(By.xpath("/html/body/div[3]/div[1]/span")).getText());

        driver.findElement(By.linkText("Submit another tool")).click();
        assertEquals("Add new tool", driver.findElement(By.xpath("/html/body/div[3]/h3")).getText());
    }
}
