package tests;// Generated by Selenium IDE

import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static io.github.bonigarcia.wdm.DriverManagerType.CHROME;
import static org.junit.Assert.assertEquals;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.JavascriptExecutor;

import java.util.*;
import java.util.concurrent.TimeUnit;

public class AddNewOrderTest {

    private static final String ADMIN_USERNAME = "krusty";
    private static final String ADMIN_PASSWORD = "krab";

    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() {
        WebDriverManager.getInstance(CHROME).setup();
        driver = new ChromeDriver();

        js = (JavascriptExecutor) driver;
        vars = new HashMap<>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void addNewOrder() {
        driver.get("http://localhost:8080/");
        driver.manage().window().setSize(new Dimension(1552, 840));
        driver.findElement(By.linkText("Sign in")).click();
        driver.findElement(By.name("username")).sendKeys(ADMIN_USERNAME);
        driver.findElement(By.cssSelector(".segment")).click();
        driver.findElement(By.cssSelector("body")).click();
        driver.findElement(By.name("password")).sendKeys(ADMIN_PASSWORD);
        driver.findElement(By.cssSelector(".basic")).click();
        driver.findElement(By.linkText("Create new order")).click();
        driver.findElement(By.id("position")).click();
        {
            WebElement dropdown = driver.findElement(By.id("position"));
            dropdown.findElement(By.xpath("//option[. = 'Krusty Deluxe']")).click();
        }
        driver.findElement(By.cssSelector("body")).click();
        driver.findElement(By.id("value")).clear();
        driver.findElement(By.id("value")).sendKeys("7");
        driver.findElement(By.cssSelector(".blue")).click();

        System.out.println(driver.findElement(By.xpath("/html/body/div[3]/p[1]")).getText());
        System.out.println(driver.findElement(By.xpath("/html/body/div[3]/p[2]")).getText());

        assertEquals("Position: Krusty Deluxe", driver.findElement(By.xpath("/html/body/div[3]/p[1]")).getText());
        assertEquals("Count: 7", driver.findElement(By.xpath("/html/body/div[3]/p[2]")).getText());

        driver.findElement(By.linkText("Submit another order")).click();
        assertEquals("Register new order", driver.findElement(By.xpath("/html/body/div[3]/h3")).getText());

    }
}
