package tests;// Generated by Selenium IDE

import io.github.bonigarcia.wdm.WebDriverManager;
import org.apache.commons.lang3.RandomStringUtils;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static io.github.bonigarcia.wdm.DriverManagerType.CHROME;
import static org.junit.Assert.*;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;


import java.util.*;
import java.util.concurrent.TimeUnit;

public class AddUserTest {

    private static final String ADMIN_USERNAME = "krusty";
    private static final String ADMIN_PASSWORD = "krab";

    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() {
        WebDriverManager.getInstance(CHROME).setup();
        driver = new ChromeDriver();

        js = (JavascriptExecutor) driver;
        vars = new HashMap<>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void addUser() {
        driver.get("http://localhost:8080/");
        driver.manage().window().setSize(new Dimension(1552, 840));
        driver.findElement(By.linkText("Sign in")).click();
        driver.findElement(By.cssSelector("body")).click();
        driver.findElement(By.name("username")).sendKeys(ADMIN_USERNAME);
        driver.findElement(By.cssSelector(".segment")).click();
        driver.findElement(By.cssSelector("body")).click();
        driver.findElement(By.name("password")).sendKeys(ADMIN_PASSWORD);
        driver.findElement(By.cssSelector(".basic")).click();
        driver.findElement(By.linkText("Add new user")).click();
        driver.findElement(By.id("login")).click();
        String chefUsername = generateRandomString();
        driver.findElement(By.id("login")).sendKeys(chefUsername);
        driver.findElement(By.cssSelector("button")).click();
        driver.findElement(By.id("password")).click();
        driver.findElement(By.id("password")).click();
        String password = driver.findElement(By.id("password")).getAttribute("value");
        System.out.println(password);

        driver.findElement(By.cssSelector(".form")).click();

        driver.findElement(By.id("resourceSelect")).click();
        driver.findElement(By.cssSelector(".blue")).click();
        driver.findElement(By.cssSelector(".red")).click();
        driver.findElement(By.cssSelector("body")).click();
        driver.findElement(By.name("username")).clear();
        driver.findElement(By.name("password")).clear();
        driver.findElement(By.name("username")).sendKeys(chefUsername);
        driver.findElement(By.cssSelector("body")).click();
        driver.findElement(By.name("password")).sendKeys(password);
        driver.findElement(By.cssSelector(".basic")).click();
        driver.manage().timeouts().implicitlyWait(3, TimeUnit.SECONDS);
        driver.findElement(By.linkText("Cooking")).click();

        assertEquals("Cooking", driver.findElement(By.xpath("/html/body/div[3]/h3")).getText());
    }

    private String generateRandomString() {
        int length = 10;
        boolean useLetters = true;
        boolean useNumbers = false;
        return RandomStringUtils.random(length, useLetters, useNumbers);
    }
}
